services:
  - type: web
    name: stufe7-web
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST_HEADER
        value: x-forwarded-host
      - key: PROTOCOL_HEADER
        value: x-forwarded-proto
      - key: PUBLIC_ADMIN_ORIGIN
        value: https://admin.stufe7.com

  - type: web
    name: stufe7-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /health
    envVars:
      - key: APP_ENV
        value: staging
      - key: CORS_ORIGINS
        sync: false
