services:
  - type: web
    name: stufe7-web
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: stufe7-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /health
    envVars:
      - key: APP_ENV
        value: staging
      - key: CORS_ORIGINS
        sync: false
