export const COUNTRIES: { code: string; name: string }[] = [
	{ code: 'SG', name: 'Singapore' },
	{ code: 'MY', name: 'Malaysia' },
	{ code: 'ID', name: 'Indonesia' },
	{ code: 'TH', name: 'Thailand' },
	{ code: 'VN', name: 'Vietnam' },
	{ code: 'PH', name: 'Philippines' },
	{ code: 'AU', name: 'Australia' },
	{ code: 'NZ', name: 'New Zealand' },
	{ code: 'IN', name: 'India' },
	{ code: 'JP', name: 'Japan' },
	{ code: 'KR', name: 'South Korea' },
	{ code: 'CN', name: 'China' },
	{ code: 'HK', name: 'Hong Kong' },
	{ code: 'TW', name: 'Taiwan' },
	{ code: 'AE', name: 'United Arab Emirates' },
	{ code: 'SA', name: 'Saudi Arabia' },
	{ code: 'QA', name: 'Qatar' },
	{ code: 'US', name: 'United States' },
	{ code: 'CA', name: 'Canada' },
	{ code: 'MX', name: 'Mexico' },
	{ code: 'GB', name: 'United Kingdom' },
	{ code: 'IE', name: 'Ireland' },
	{ code: 'DE', name: 'Germany' },
	{ code: 'FR', name: 'France' },
	{ code: 'NL', name: 'Netherlands' },
	{ code: 'BE', name: 'Belgium' },
	{ code: 'CH', name: 'Switzerland' },
	{ code: 'AT', name: 'Austria' },
	{ code: 'IT', name: 'Italy' },
	{ code: 'ES', name: 'Spain' },
	{ code: 'PT', name: 'Portugal' },
	{ code: 'SE', name: 'Sweden' },
	{ code: 'NO', name: 'Norway' },
	{ code: 'DK', name: 'Denmark' },
	{ code: 'FI', name: 'Finland' },
	{ code: 'PL', name: 'Poland' },
	{ code: 'CZ', name: 'Czechia' },
	{ code: 'BR', name: 'Brazil' },
	{ code: 'ZA', name: 'South Africa' },
	{ code: 'NG', name: 'Nigeria' },
	{ code: 'KE', name: 'Kenya' },
	{ code: 'EG', name: 'Egypt' }
];
